color_list_1 = set(["White", "Black", "Red"])
car_list = set(["Benz", "Toyota"])
print("Original set elements:")
print(color_list_1)
print(car_list)
print("\nDifferenct of color_list_1 and color_list_2:")
print(color_list_1.difference(car_list))
print("\nDifferenct of color_list_2 and color_list_1:")
print(car_list.difference(color_list_1))
